default_platform(:ios)

platform :ios do
  desc "Build IPA for TestFlight"
  lane :build_ipa do
    # Disable automatic signing first
    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: "L2J8AW86LW",
      code_sign_identity: "Apple Distribution: Arman J",
      profile_name: "com.***app.app"
    )
    
    # Build Flutter
    sh("cd .. && flutter build ios --release --no-codesign")
    
    # Update provisioning
    update_project_provisioning(
      xcodeproj: "Runner.xcodeproj",
      profile: "build_pp.mobileprovision",
      target_filter: "Runner",
      build_configuration: "Release"
    )
    
    # Update team
    update_project_team(
      path: "Runner.xcodeproj",
      teamid: "L2J8AW86LW"
    )
    
    # Build and sign the archive
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      export_method: "app-store",
      codesigning_identity: "Apple Distribution: Arman J"
    )
  end
end